
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIR = 21;
  public static final int IDF = 13;
  public static final int CLASS = 12;
  public static final int PLUS = 5;
  public static final int TEST_NON_EGAL = 11;
  public static final int LIR = 20;
  public static final int SUP = 9;
  public static final int STATUT = 17;
  public static final int FOIS = 7;
  public static final int PARENTHESE_FERMER = 4;
  public static final int VIRGULE = 15;
  public static final int TEST_EGAL = 10;
  public static final int MOINS = 6;
  public static final int INF = 8;
  public static final int CSTE_ENT = 2;
  public static final int EGALE = 19;
  public static final int TYPE = 18;
  public static final int CSTE_CHAINE = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PARENTHESE_OUVERT = 3;
  public static final int POINT_VIRGULE = 16;
  public static final int FIN = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CSTE_ENT",
  "PARENTHESE_OUVERT",
  "PARENTHESE_FERMER",
  "PLUS",
  "MOINS",
  "FOIS",
  "INF",
  "SUP",
  "TEST_EGAL",
  "TEST_NON_EGAL",
  "CLASS",
  "IDF",
  "FIN",
  "VIRGULE",
  "POINT_VIRGULE",
  "STATUT",
  "TYPE",
  "EGALE",
  "LIR",
  "ECRIR",
  "CSTE_CHAINE"
  };
}

