
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int pointvirgule = 17;
  public static final int parenthese_ouvert = 4;
  public static final int test_egale = 12;
  public static final int sup = 11;
  public static final int cste_ent = 2;
  public static final int ecrire = 22;
  public static final int type = 20;
  public static final int cste_chaine = 3;
  public static final int inf = 10;
  public static final int parenthese_fermer = 5;
  public static final int bool = 14;
  public static final int EOF = 0;
  public static final int statut = 19;
  public static final int error = 1;
  public static final int virgule = 21;
  public static final int classe = 15;
  public static final int plus = 6;
  public static final int lire = 23;
  public static final int fin = 16;
  public static final int moins = 7;
  public static final int fois = 8;
  public static final int egale = 24;
  public static final int diviser = 9;
  public static final int idf = 18;
  public static final int test_different = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cste_ent",
  "cste_chaine",
  "parenthese_ouvert",
  "parenthese_fermer",
  "plus",
  "moins",
  "fois",
  "diviser",
  "inf",
  "sup",
  "test_egale",
  "test_different",
  "bool",
  "classe",
  "fin",
  "pointvirgule",
  "idf",
  "statut",
  "type",
  "virgule",
  "ecrire",
  "lire",
  "egale"
  };
}

