
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int CSTE_ENT = 2;
  public static final int BOOL = 13;
  public static final int EGALE = 11;
  public static final int DIVISER = 8;
  public static final int DIFFERENT = 12;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int INF = 9;
  public static final int error = 1;
  public static final int PARENTHESE_OUVERT = 3;
  public static final int PARENTHESE_FERMER = 4;
  public static final int MOINS = 6;
  public static final int FOIS = 7;
  public static final int SUP = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CSTE_ENT",
  "PARENTHESE_OUVERT",
  "PARENTHESE_FERMER",
  "PLUS",
  "MOINS",
  "FOIS",
  "DIVISER",
  "INF",
  "SUP",
  "EGALE",
  "DIFFERENT",
  "BOOL"
  };
}

