
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int parenthese_ouvert = 3;
  public static final int pointvirgule = 16;
  public static final int sup = 10;
  public static final int cste_ent = 2;
  public static final int inf = 9;
  public static final int parenthese_fermer = 4;
  public static final int bool = 13;
  public static final int EOF = 0;
  public static final int different = 12;
  public static final int error = 1;
  public static final int classe = 14;
  public static final int plus = 5;
  public static final int fin = 15;
  public static final int moins = 6;
  public static final int fois = 7;
  public static final int diviser = 8;
  public static final int egale = 11;
  public static final int idf = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cste_ent",
  "parenthese_ouvert",
  "parenthese_fermer",
  "plus",
  "moins",
  "fois",
  "diviser",
  "inf",
  "sup",
  "egale",
  "different",
  "bool",
  "classe",
  "fin",
  "pointvirgule",
  "idf"
  };
}

